# Generated by Django 5.1 on 2024-10-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoManager', '0011_videoresponse_videoresponsepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresponse',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videoresponsepart',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
