# Generated by Django 5.1 on 2024-10-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoManager', '0012_alter_videoresponse_url_alter_videoresponsepart_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresponse',
            name='user',
        ),
    ]
